# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_native
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_native)
  nanovg_config = debug_native
  example_gl2_config = debug_native
  example_gl3_config = debug_native
  example_gl2_msaa_config = debug_native
  example_gl3_msaa_config = debug_native
  example_fbo_config = debug_native
  example_gles2_config = debug_native
  example_gles3_config = debug_native
endif
ifeq ($(config),debug_x64)
  nanovg_config = debug_x64
  example_gl2_config = debug_x64
  example_gl3_config = debug_x64
  example_gl2_msaa_config = debug_x64
  example_gl3_msaa_config = debug_x64
  example_fbo_config = debug_x64
  example_gles2_config = debug_x64
  example_gles3_config = debug_x64
endif
ifeq ($(config),debug_x32)
  nanovg_config = debug_x32
  example_gl2_config = debug_x32
  example_gl3_config = debug_x32
  example_gl2_msaa_config = debug_x32
  example_gl3_msaa_config = debug_x32
  example_fbo_config = debug_x32
  example_gles2_config = debug_x32
  example_gles3_config = debug_x32
endif
ifeq ($(config),release_native)
  nanovg_config = release_native
  example_gl2_config = release_native
  example_gl3_config = release_native
  example_gl2_msaa_config = release_native
  example_gl3_msaa_config = release_native
  example_fbo_config = release_native
  example_gles2_config = release_native
  example_gles3_config = release_native
endif
ifeq ($(config),release_x64)
  nanovg_config = release_x64
  example_gl2_config = release_x64
  example_gl3_config = release_x64
  example_gl2_msaa_config = release_x64
  example_gl3_msaa_config = release_x64
  example_fbo_config = release_x64
  example_gles2_config = release_x64
  example_gles3_config = release_x64
endif
ifeq ($(config),release_x32)
  nanovg_config = release_x32
  example_gl2_config = release_x32
  example_gl3_config = release_x32
  example_gl2_msaa_config = release_x32
  example_gl3_msaa_config = release_x32
  example_fbo_config = release_x32
  example_gles2_config = release_x32
  example_gles3_config = release_x32
endif

PROJECTS := nanovg example_gl2 example_gl3 example_gl2_msaa example_gl3_msaa example_fbo example_gles2 example_gles3

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

nanovg:
ifneq (,$(nanovg_config))
	@echo "==== Building nanovg ($(nanovg_config)) ===="
	@${MAKE} --no-print-directory -C . -f nanovg.make config=$(nanovg_config)
endif

example_gl2: nanovg
ifneq (,$(example_gl2_config))
	@echo "==== Building example_gl2 ($(example_gl2_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_gl2.make config=$(example_gl2_config)
endif

example_gl3: nanovg
ifneq (,$(example_gl3_config))
	@echo "==== Building example_gl3 ($(example_gl3_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_gl3.make config=$(example_gl3_config)
endif

example_gl2_msaa: nanovg
ifneq (,$(example_gl2_msaa_config))
	@echo "==== Building example_gl2_msaa ($(example_gl2_msaa_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_gl2_msaa.make config=$(example_gl2_msaa_config)
endif

example_gl3_msaa: nanovg
ifneq (,$(example_gl3_msaa_config))
	@echo "==== Building example_gl3_msaa ($(example_gl3_msaa_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_gl3_msaa.make config=$(example_gl3_msaa_config)
endif

example_fbo: nanovg
ifneq (,$(example_fbo_config))
	@echo "==== Building example_fbo ($(example_fbo_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_fbo.make config=$(example_fbo_config)
endif

example_gles2: nanovg
ifneq (,$(example_gles2_config))
	@echo "==== Building example_gles2 ($(example_gles2_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_gles2.make config=$(example_gles2_config)
endif

example_gles3: nanovg
ifneq (,$(example_gles3_config))
	@echo "==== Building example_gles3 ($(example_gles3_config)) ===="
	@${MAKE} --no-print-directory -C . -f example_gles3.make config=$(example_gles3_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f nanovg.make clean
	@${MAKE} --no-print-directory -C . -f example_gl2.make clean
	@${MAKE} --no-print-directory -C . -f example_gl3.make clean
	@${MAKE} --no-print-directory -C . -f example_gl2_msaa.make clean
	@${MAKE} --no-print-directory -C . -f example_gl3_msaa.make clean
	@${MAKE} --no-print-directory -C . -f example_fbo.make clean
	@${MAKE} --no-print-directory -C . -f example_gles2.make clean
	@${MAKE} --no-print-directory -C . -f example_gles3.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_native"
	@echo "  debug_x64"
	@echo "  debug_x32"
	@echo "  release_native"
	@echo "  release_x64"
	@echo "  release_x32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   nanovg"
	@echo "   example_gl2"
	@echo "   example_gl3"
	@echo "   example_gl2_msaa"
	@echo "   example_gl3_msaa"
	@echo "   example_fbo"
	@echo "   example_gles2"
	@echo "   example_gles3"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"